# Generated by Django 3.1 on 2020-09-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.URLField(),
        ),
    ]
